name: UPDATE Build and deploy to the Stage env
on:
  pull_request:
    types:
      - closed
    branches:
      - stage
jobs:
  delivery:
    if: github.event.pull_request.merged == true
    name: Code Delivery
    runs-on: ubuntu-22.04
    steps:
      - name: Pull code and restart container
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd burning-wallet-app
            echo "PUBLIC_API_URL=${{ secrets.API_URL }}" > .env
            echo "ORIGIN=${{ secrets.APP_ORIGIN }}" >> .env
            echo "HOST=${{ secrets.APP_HOST }}" >> .env
            echo "PORT=${{ secrets.APP_PORT }}" >> .env
            git checkout stage
            git fetch && git pull origin stage --autostash
            docker build -t burning-wallet-app ./
            docker restart burning-wallet-frontend
