name: UPDATE Build and deploy to the Stage env
on:
  pull_request:
    types:
      - closed
    branches:
      - stage
jobs:
  delivery:
    if: ${{ github.event.label.name == 'updateStage' }} && github.event.pull_request.merged == true
    name: Code Delivery
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout and pull branch
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          git checkout stage
          git fetch && git pull
          docker build -t burning-wallet-app ./
          docker restart burning-wallet-frontend
